# Generated by Django 5.0.4 on 2024-04-19 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="notification_task_id",
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="reminder_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
